// ---------------------------------------------------------------------------
// Grocery Mock Data
// ---------------------------------------------------------------------------

import type { GroceryCategory, GroceryProduct } from '../../../types/grocery';
import type { ID, Timestamp } from '../../../types/common';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const id = (value: string) => value as ID;
const ts = (value: string) => value as Timestamp;

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

const MOCK_CATEGORIES: GroceryCategory[] = [
  {
    id: id('cat-1'),
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    description: 'Fresh produce daily',
    imageUrl: '/images/categories/fruits.jpg',
    iconName: 'leaf',
    color: '#22c55e',
    productCount: 12,
    order: 1,
  },
  {
    id: id('cat-2'),
    name: 'Dairy & Eggs',
    slug: 'dairy-eggs',
    description: 'Farm fresh dairy products',
    imageUrl: '/images/categories/dairy.jpg',
    iconName: 'milk',
    color: '#3b82f6',
    productCount: 8,
    order: 2,
  },
  {
    id: id('cat-3'),
    name: 'Bakery',
    slug: 'bakery',
    description: 'Freshly baked goods',
    imageUrl: '/images/categories/bakery.jpg',
    iconName: 'bread',
    color: '#f59e0b',
    productCount: 6,
    order: 3,
  },
  {
    id: id('cat-4'),
    name: 'Meat & Seafood',
    slug: 'meat-seafood',
    description: 'Premium cuts and fresh fish',
    imageUrl: '/images/categories/meat.jpg',
    iconName: 'drumstick',
    color: '#ef4444',
    productCount: 8,
    order: 4,
  },
  {
    id: id('cat-5'),
    name: 'Beverages',
    slug: 'beverages',
    description: 'Drinks for every occasion',
    imageUrl: '/images/categories/beverages.jpg',
    iconName: 'coffee',
    color: '#8b5cf6',
    productCount: 10,
    order: 5,
  },
  {
    id: id('cat-6'),
    name: 'Snacks',
    slug: 'snacks',
    description: 'Chips, nuts, and more',
    imageUrl: '/images/categories/snacks.jpg',
    iconName: 'cookie',
    color: '#f97316',
    productCount: 8,
    order: 6,
  },
  {
    id: id('cat-7'),
    name: 'Frozen Foods',
    slug: 'frozen-foods',
    description: 'Frozen meals and treats',
    imageUrl: '/images/categories/frozen.jpg',
    iconName: 'snowflake',
    color: '#06b6d4',
    productCount: 6,
    order: 7,
  },
  {
    id: id('cat-8'),
    name: 'Pantry Staples',
    slug: 'pantry-staples',
    description: 'Essential cooking ingredients',
    imageUrl: '/images/categories/pantry.jpg',
    iconName: 'jar',
    color: '#a3722b',
    productCount: 10,
    order: 8,
  },
];

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

const cat = (slug: string) =>
  MOCK_CATEGORIES.find((c) => c.slug === slug)!;

const MOCK_PRODUCTS: GroceryProduct[] = [
  // -----------------------------------------------------------------------
  // Fruits & Vegetables
  // -----------------------------------------------------------------------
  {
    id: id('prod-1'),
    name: 'Organic Bananas',
    slug: 'organic-bananas',
    description:
      'Sweet and creamy organic bananas, perfect for smoothies, baking, or a quick snack on the go. Sourced from sustainable farms.',
    price: 1.49,
    originalPrice: 1.99,
    unit: 'lb',
    category: cat('fruits-vegetables'),
    imageUrl: '/images/products/bananas.jpg',
    modelUrl: null,
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    stockQuantity: 150,
    nutritionFacts: {
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.4,
      fiber: 3.1,
      sodium: 1,
    },
    tags: ['organic', 'fruit', 'tropical', 'potassium'],
    badges: ['organic', 'sale'],
    weight: 453,
    dimensions: { width: 15, height: 4, depth: 4 },
    createdAt: ts('2025-01-15T10:00:00Z'),
    updatedAt: ts('2025-06-01T12:00:00Z'),
  },
  {
    id: id('prod-2'),
    name: 'Fresh Strawberries',
    slug: 'fresh-strawberries',
    description:
      'Plump, juicy strawberries bursting with flavour. Ideal for desserts, salads, or eating fresh.',
    price: 4.99,
    originalPrice: 4.99,
    unit: 'pack',
    category: cat('fruits-vegetables'),
    imageUrl: '/images/products/strawberries.jpg',
    modelUrl: null,
    rating: 4.5,
    reviewCount: 189,
    inStock: true,
    stockQuantity: 80,
    nutritionFacts: {
      calories: 49,
      protein: 1,
      carbs: 12,
      fat: 0.5,
      fiber: 3,
      sodium: 2,
    },
    tags: ['fruit', 'berries', 'vitamin-c'],
    badges: ['popular'],
    weight: 454,
    dimensions: { width: 12, height: 8, depth: 12 },
    createdAt: ts('2025-02-10T10:00:00Z'),
    updatedAt: ts('2025-06-01T12:00:00Z'),
  },
  {
    id: id('prod-3'),
    name: 'Hass Avocados',
    slug: 'hass-avocados',
    description:
      'Creamy Hass avocados, perfect for guacamole, toast, or salads. Rich in healthy fats and fibre.',
    price: 1.99,
    originalPrice: 2.49,
    unit: 'each',
    category: cat('fruits-vegetables'),
    imageUrl: '/images/products/avocados.jpg',
    modelUrl: null,
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
    stockQuantity: 200,
    nutritionFacts: {
      calories: 240,
      protein: 3,
      carbs: 13,
      fat: 22,
      fiber: 10,
      sodium: 11,
    },
    tags: ['fruit', 'healthy-fats', 'keto-friendly'],
    badges: ['sale'],
    weight: 200,
    dimensions: { width: 7, height: 10, depth: 7 },
    createdAt: ts('2025-01-20T10:00:00Z'),
    updatedAt: ts('2025-06-02T08:00:00Z'),
  },
  {
    id: id('prod-4'),
    name: 'Red Apples',
    slug: 'red-apples',
    description:
      'Crisp and sweet red apples. A classic everyday fruit packed with vitamins and antioxidants.',
    price: 3.49,
    originalPrice: 3.49,
    unit: 'lb',
    category: cat('fruits-vegetables'),
    imageUrl: '/images/products/red-apples.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    stockQuantity: 120,
    nutritionFacts: {
      calories: 95,
      protein: 0.5,
      carbs: 25,
      fat: 0.3,
      fiber: 4.4,
      sodium: 2,
    },
    tags: ['fruit', 'fiber', 'snack'],
    badges: [],
    weight: 200,
    dimensions: { width: 8, height: 8, depth: 8 },
    createdAt: ts('2025-01-10T10:00:00Z'),
    updatedAt: ts('2025-05-15T10:00:00Z'),
  },
  {
    id: id('prod-5'),
    name: 'Baby Spinach',
    slug: 'baby-spinach',
    description:
      'Tender baby spinach leaves, pre-washed and ready to eat. Great for salads, smoothies, and cooking.',
    price: 3.99,
    originalPrice: 3.99,
    unit: 'pack',
    category: cat('fruits-vegetables'),
    imageUrl: '/images/products/baby-spinach.jpg',
    modelUrl: null,
    rating: 4.4,
    reviewCount: 98,
    inStock: true,
    stockQuantity: 60,
    nutritionFacts: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sodium: 79,
    },
    tags: ['vegetable', 'leafy-green', 'iron', 'organic'],
    badges: ['organic'],
    weight: 142,
    dimensions: { width: 18, height: 6, depth: 12 },
    createdAt: ts('2025-03-01T10:00:00Z'),
    updatedAt: ts('2025-06-03T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Dairy & Eggs
  // -----------------------------------------------------------------------
  {
    id: id('prod-6'),
    name: 'Whole Milk',
    slug: 'whole-milk',
    description:
      'Fresh whole milk with a rich, creamy taste. Perfect for drinking, cooking, and baking.',
    price: 4.29,
    originalPrice: 4.29,
    unit: 'each',
    category: cat('dairy-eggs'),
    imageUrl: '/images/products/whole-milk.jpg',
    modelUrl: null,
    rating: 4.8,
    reviewCount: 445,
    inStock: true,
    stockQuantity: 90,
    nutritionFacts: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
      fiber: 0,
      sodium: 105,
    },
    tags: ['dairy', 'calcium', 'protein', 'essential'],
    badges: ['popular'],
    weight: 3785,
    dimensions: { width: 10, height: 25, depth: 10 },
    createdAt: ts('2025-01-05T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-7'),
    name: 'Greek Yogurt',
    slug: 'greek-yogurt',
    description:
      'Thick and creamy Greek yogurt with double the protein. Available in plain for maximum versatility.',
    price: 5.99,
    originalPrice: 6.49,
    unit: 'each',
    category: cat('dairy-eggs'),
    imageUrl: '/images/products/greek-yogurt.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 278,
    inStock: true,
    stockQuantity: 65,
    nutritionFacts: {
      calories: 100,
      protein: 17,
      carbs: 6,
      fat: 0.7,
      fiber: 0,
      sodium: 60,
    },
    tags: ['dairy', 'high-protein', 'probiotics', 'breakfast'],
    badges: ['sale'],
    weight: 907,
    dimensions: { width: 12, height: 10, depth: 12 },
    createdAt: ts('2025-02-01T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-8'),
    name: 'Free-Range Eggs',
    slug: 'free-range-eggs',
    description:
      'Large free-range eggs from pasture-raised hens. Rich golden yolks and superior flavour.',
    price: 6.49,
    originalPrice: 6.49,
    unit: 'dozen',
    category: cat('dairy-eggs'),
    imageUrl: '/images/products/eggs.jpg',
    modelUrl: null,
    rating: 4.9,
    reviewCount: 512,
    inStock: true,
    stockQuantity: 100,
    nutritionFacts: {
      calories: 70,
      protein: 6,
      carbs: 0,
      fat: 5,
      fiber: 0,
      sodium: 70,
    },
    tags: ['eggs', 'free-range', 'protein', 'essential'],
    badges: ['organic'],
    weight: 720,
    dimensions: { width: 20, height: 8, depth: 10 },
    createdAt: ts('2025-01-08T10:00:00Z'),
    updatedAt: ts('2025-05-20T10:00:00Z'),
  },
  {
    id: id('prod-9'),
    name: 'Sharp Cheddar Cheese',
    slug: 'sharp-cheddar-cheese',
    description:
      'Aged sharp cheddar with a bold, tangy flavour. Perfect for sandwiches, burgers, or a cheese board.',
    price: 7.99,
    originalPrice: 7.99,
    unit: 'each',
    category: cat('dairy-eggs'),
    imageUrl: '/images/products/cheddar.jpg',
    modelUrl: null,
    rating: 4.5,
    reviewCount: 167,
    inStock: true,
    stockQuantity: 45,
    nutritionFacts: {
      calories: 110,
      protein: 7,
      carbs: 1,
      fat: 9,
      fiber: 0,
      sodium: 180,
    },
    tags: ['dairy', 'cheese', 'aged', 'calcium'],
    badges: [],
    weight: 227,
    dimensions: { width: 10, height: 5, depth: 6 },
    createdAt: ts('2025-02-15T10:00:00Z'),
    updatedAt: ts('2025-05-28T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Bakery
  // -----------------------------------------------------------------------
  {
    id: id('prod-10'),
    name: 'Sourdough Bread',
    slug: 'sourdough-bread',
    description:
      'Artisan sourdough bread with a crispy crust and tangy, chewy interior. Naturally leavened over 24 hours.',
    price: 5.49,
    originalPrice: 5.49,
    unit: 'each',
    category: cat('bakery'),
    imageUrl: '/images/products/sourdough.jpg',
    modelUrl: null,
    rating: 4.8,
    reviewCount: 321,
    inStock: true,
    stockQuantity: 30,
    nutritionFacts: {
      calories: 120,
      protein: 4,
      carbs: 24,
      fat: 0.5,
      fiber: 1,
      sodium: 230,
    },
    tags: ['bread', 'artisan', 'sourdough', 'fermented'],
    badges: ['popular'],
    weight: 680,
    dimensions: { width: 20, height: 12, depth: 12 },
    createdAt: ts('2025-03-01T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-11'),
    name: 'Butter Croissants',
    slug: 'butter-croissants',
    description:
      'Flaky, golden butter croissants made with real French butter. Baked fresh every morning.',
    price: 4.99,
    originalPrice: 5.99,
    unit: 'pack',
    category: cat('bakery'),
    imageUrl: '/images/products/croissants.jpg',
    modelUrl: null,
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    stockQuantity: 40,
    nutritionFacts: {
      calories: 230,
      protein: 5,
      carbs: 26,
      fat: 12,
      fiber: 1,
      sodium: 310,
    },
    tags: ['bakery', 'pastry', 'french', 'breakfast'],
    badges: ['sale', 'new'],
    weight: 280,
    dimensions: { width: 18, height: 10, depth: 14 },
    createdAt: ts('2025-04-01T10:00:00Z'),
    updatedAt: ts('2025-06-03T10:00:00Z'),
  },
  {
    id: id('prod-12'),
    name: 'Everything Bagels',
    slug: 'everything-bagels',
    description:
      'Chewy New York-style bagels topped with sesame, poppy seeds, onion, garlic, and salt.',
    price: 4.49,
    originalPrice: 4.49,
    unit: 'pack',
    category: cat('bakery'),
    imageUrl: '/images/products/bagels.jpg',
    modelUrl: null,
    rating: 4.4,
    reviewCount: 145,
    inStock: true,
    stockQuantity: 50,
    nutritionFacts: {
      calories: 270,
      protein: 10,
      carbs: 53,
      fat: 2,
      fiber: 2,
      sodium: 490,
    },
    tags: ['bakery', 'bagel', 'breakfast'],
    badges: [],
    weight: 510,
    dimensions: { width: 16, height: 8, depth: 16 },
    createdAt: ts('2025-03-15T10:00:00Z'),
    updatedAt: ts('2025-05-20T10:00:00Z'),
  },
  {
    id: id('prod-13'),
    name: 'Chocolate Cake',
    slug: 'chocolate-cake',
    description:
      'Rich, moist chocolate cake with velvety ganache frosting. Made with premium Belgian cocoa.',
    price: 18.99,
    originalPrice: 22.99,
    unit: 'each',
    category: cat('bakery'),
    imageUrl: '/images/products/chocolate-cake.jpg',
    modelUrl: null,
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
    stockQuantity: 12,
    nutritionFacts: {
      calories: 350,
      protein: 5,
      carbs: 50,
      fat: 16,
      fiber: 2,
      sodium: 370,
    },
    tags: ['bakery', 'cake', 'dessert', 'chocolate', 'celebration'],
    badges: ['sale', 'popular'],
    weight: 900,
    dimensions: { width: 22, height: 12, depth: 22 },
    createdAt: ts('2025-04-10T10:00:00Z'),
    updatedAt: ts('2025-06-04T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Meat & Seafood
  // -----------------------------------------------------------------------
  {
    id: id('prod-14'),
    name: 'Chicken Breast',
    slug: 'chicken-breast',
    description:
      'Boneless, skinless chicken breast fillets. Lean, versatile protein source for grilling, baking, or stir-frying.',
    price: 8.99,
    originalPrice: 8.99,
    unit: 'lb',
    category: cat('meat-seafood'),
    imageUrl: '/images/products/chicken-breast.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 389,
    inStock: true,
    stockQuantity: 75,
    nutritionFacts: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sodium: 74,
    },
    tags: ['meat', 'chicken', 'lean-protein', 'high-protein'],
    badges: ['popular'],
    weight: 907,
    dimensions: { width: 18, height: 5, depth: 12 },
    createdAt: ts('2025-01-12T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-15'),
    name: 'Atlantic Salmon Fillet',
    slug: 'atlantic-salmon-fillet',
    description:
      'Fresh Atlantic salmon fillets, rich in omega-3 fatty acids. Sustainably farmed with no antibiotics.',
    price: 12.99,
    originalPrice: 14.99,
    unit: 'lb',
    category: cat('meat-seafood'),
    imageUrl: '/images/products/salmon.jpg',
    modelUrl: null,
    rating: 4.7,
    reviewCount: 256,
    inStock: true,
    stockQuantity: 40,
    nutritionFacts: {
      calories: 208,
      protein: 20,
      carbs: 0,
      fat: 13,
      fiber: 0,
      sodium: 59,
    },
    tags: ['seafood', 'fish', 'omega-3', 'sustainable'],
    badges: ['sale'],
    weight: 680,
    dimensions: { width: 20, height: 4, depth: 10 },
    createdAt: ts('2025-02-20T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-16'),
    name: 'Ground Beef 85/15',
    slug: 'ground-beef',
    description:
      'Premium ground beef with an 85/15 lean-to-fat ratio. Perfect for burgers, tacos, and pasta sauces.',
    price: 7.49,
    originalPrice: 7.49,
    unit: 'lb',
    category: cat('meat-seafood'),
    imageUrl: '/images/products/ground-beef.jpg',
    modelUrl: null,
    rating: 4.4,
    reviewCount: 201,
    inStock: true,
    stockQuantity: 60,
    nutritionFacts: {
      calories: 215,
      protein: 26,
      carbs: 0,
      fat: 13,
      fiber: 0,
      sodium: 75,
    },
    tags: ['meat', 'beef', 'ground', 'protein'],
    badges: [],
    weight: 454,
    dimensions: { width: 14, height: 6, depth: 10 },
    createdAt: ts('2025-01-25T10:00:00Z'),
    updatedAt: ts('2025-05-30T10:00:00Z'),
  },
  {
    id: id('prod-17'),
    name: 'Jumbo Shrimp',
    slug: 'jumbo-shrimp',
    description:
      'Wild-caught jumbo shrimp, peeled and deveined. Ready to cook for stir-fries, pastas, or grilling.',
    price: 14.99,
    originalPrice: 16.99,
    unit: 'lb',
    category: cat('meat-seafood'),
    imageUrl: '/images/products/shrimp.jpg',
    modelUrl: null,
    rating: 4.5,
    reviewCount: 178,
    inStock: true,
    stockQuantity: 35,
    nutritionFacts: {
      calories: 99,
      protein: 24,
      carbs: 0,
      fat: 0.3,
      fiber: 0,
      sodium: 111,
    },
    tags: ['seafood', 'shrimp', 'wild-caught', 'low-calorie'],
    badges: ['sale'],
    weight: 454,
    dimensions: { width: 16, height: 5, depth: 12 },
    createdAt: ts('2025-03-05T10:00:00Z'),
    updatedAt: ts('2025-06-03T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Beverages
  // -----------------------------------------------------------------------
  {
    id: id('prod-18'),
    name: 'Fresh Orange Juice',
    slug: 'fresh-orange-juice',
    description:
      'Not-from-concentrate fresh-squeezed orange juice. No added sugar, no preservatives. Pure citrus goodness.',
    price: 5.99,
    originalPrice: 5.99,
    unit: 'each',
    category: cat('beverages'),
    imageUrl: '/images/products/orange-juice.jpg',
    modelUrl: null,
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    stockQuantity: 70,
    nutritionFacts: {
      calories: 110,
      protein: 2,
      carbs: 26,
      fat: 0,
      fiber: 0,
      sodium: 0,
    },
    tags: ['juice', 'orange', 'vitamin-c', 'no-sugar-added'],
    badges: [],
    weight: 1893,
    dimensions: { width: 9, height: 24, depth: 9 },
    createdAt: ts('2025-01-18T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-19'),
    name: 'Premium Coffee Beans',
    slug: 'premium-coffee-beans',
    description:
      'Single-origin Arabica coffee beans from Colombia. Medium roast with notes of chocolate and caramel.',
    price: 14.99,
    originalPrice: 14.99,
    unit: 'each',
    category: cat('beverages'),
    imageUrl: '/images/products/coffee-beans.jpg',
    modelUrl: null,
    rating: 4.8,
    reviewCount: 445,
    inStock: true,
    stockQuantity: 55,
    nutritionFacts: {
      calories: 2,
      protein: 0.3,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sodium: 5,
    },
    tags: ['coffee', 'arabica', 'single-origin', 'whole-bean'],
    badges: ['popular'],
    weight: 340,
    dimensions: { width: 10, height: 20, depth: 8 },
    createdAt: ts('2025-02-05T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-20'),
    name: 'Organic Green Tea',
    slug: 'organic-green-tea',
    description:
      'Premium organic green tea bags. Light, refreshing taste with natural antioxidants. 40 bags per box.',
    price: 6.49,
    originalPrice: 7.99,
    unit: 'pack',
    category: cat('beverages'),
    imageUrl: '/images/products/green-tea.jpg',
    modelUrl: null,
    rating: 4.3,
    reviewCount: 198,
    inStock: true,
    stockQuantity: 85,
    nutritionFacts: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sodium: 0,
    },
    tags: ['tea', 'green-tea', 'organic', 'antioxidants'],
    badges: ['organic', 'sale'],
    weight: 120,
    dimensions: { width: 8, height: 12, depth: 6 },
    createdAt: ts('2025-03-10T10:00:00Z'),
    updatedAt: ts('2025-06-03T10:00:00Z'),
  },
  {
    id: id('prod-21'),
    name: 'Sparkling Water',
    slug: 'sparkling-water',
    description:
      'Naturally carbonated mineral water. Crisp and refreshing with zero calories. Pack of 12 cans.',
    price: 7.99,
    originalPrice: 7.99,
    unit: 'pack',
    category: cat('beverages'),
    imageUrl: '/images/products/sparkling-water.jpg',
    modelUrl: null,
    rating: 4.2,
    reviewCount: 167,
    inStock: true,
    stockQuantity: 120,
    nutritionFacts: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sodium: 10,
    },
    tags: ['water', 'sparkling', 'zero-calorie', 'mineral'],
    badges: [],
    weight: 4260,
    dimensions: { width: 26, height: 14, depth: 18 },
    createdAt: ts('2025-01-22T10:00:00Z'),
    updatedAt: ts('2025-05-25T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Snacks
  // -----------------------------------------------------------------------
  {
    id: id('prod-22'),
    name: 'Sea Salt Potato Chips',
    slug: 'sea-salt-potato-chips',
    description:
      'Kettle-cooked potato chips with a light dusting of sea salt. Extra crunchy with a satisfying crunch.',
    price: 3.99,
    originalPrice: 3.99,
    unit: 'each',
    category: cat('snacks'),
    imageUrl: '/images/products/potato-chips.jpg',
    modelUrl: null,
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
    stockQuantity: 90,
    nutritionFacts: {
      calories: 150,
      protein: 2,
      carbs: 15,
      fat: 9,
      fiber: 1,
      sodium: 170,
    },
    tags: ['chips', 'potato', 'snack', 'kettle-cooked'],
    badges: [],
    weight: 227,
    dimensions: { width: 14, height: 28, depth: 8 },
    createdAt: ts('2025-02-12T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-23'),
    name: 'Roasted Mixed Nuts',
    slug: 'roasted-mixed-nuts',
    description:
      'A premium blend of almonds, cashews, pecans, and walnuts. Lightly salted and dry-roasted for full flavour.',
    price: 9.99,
    originalPrice: 11.99,
    unit: 'each',
    category: cat('snacks'),
    imageUrl: '/images/products/mixed-nuts.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    stockQuantity: 55,
    nutritionFacts: {
      calories: 170,
      protein: 5,
      carbs: 7,
      fat: 15,
      fiber: 2,
      sodium: 95,
    },
    tags: ['nuts', 'protein', 'snack', 'healthy'],
    badges: ['sale'],
    weight: 340,
    dimensions: { width: 10, height: 18, depth: 10 },
    createdAt: ts('2025-03-08T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-24'),
    name: 'Oat & Honey Granola Bars',
    slug: 'oat-honey-granola-bars',
    description:
      'Crunchy granola bars made with whole grain oats and real honey. Pack of 6 individually wrapped bars.',
    price: 4.49,
    originalPrice: 4.49,
    unit: 'pack',
    category: cat('snacks'),
    imageUrl: '/images/products/granola-bars.jpg',
    modelUrl: null,
    rating: 4.1,
    reviewCount: 145,
    inStock: true,
    stockQuantity: 100,
    nutritionFacts: {
      calories: 190,
      protein: 3,
      carbs: 29,
      fat: 7,
      fiber: 2,
      sodium: 160,
    },
    tags: ['granola', 'bars', 'oats', 'honey', 'snack'],
    badges: [],
    weight: 252,
    dimensions: { width: 18, height: 4, depth: 10 },
    createdAt: ts('2025-02-28T10:00:00Z'),
    updatedAt: ts('2025-05-28T10:00:00Z'),
  },
  {
    id: id('prod-25'),
    name: 'Dark Chocolate 72%',
    slug: 'dark-chocolate-72',
    description:
      'Rich 72% cacao dark chocolate bar. Single-origin cacao with deep, complex flavour and smooth finish.',
    price: 4.99,
    originalPrice: 4.99,
    unit: 'each',
    category: cat('snacks'),
    imageUrl: '/images/products/dark-chocolate.jpg',
    modelUrl: null,
    rating: 4.7,
    reviewCount: 267,
    inStock: true,
    stockQuantity: 70,
    nutritionFacts: {
      calories: 170,
      protein: 2,
      carbs: 13,
      fat: 12,
      fiber: 3,
      sodium: 5,
    },
    tags: ['chocolate', 'dark', 'cacao', 'antioxidants'],
    badges: ['new'],
    weight: 100,
    dimensions: { width: 8, height: 16, depth: 1 },
    createdAt: ts('2025-04-15T10:00:00Z'),
    updatedAt: ts('2025-06-04T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Frozen Foods
  // -----------------------------------------------------------------------
  {
    id: id('prod-26'),
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    description:
      'Stone-baked frozen margherita pizza with San Marzano tomato sauce, mozzarella, and fresh basil.',
    price: 7.99,
    originalPrice: 8.99,
    unit: 'each',
    category: cat('frozen-foods'),
    imageUrl: '/images/products/frozen-pizza.jpg',
    modelUrl: null,
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
    stockQuantity: 45,
    nutritionFacts: {
      calories: 290,
      protein: 12,
      carbs: 36,
      fat: 11,
      fiber: 2,
      sodium: 640,
    },
    tags: ['frozen', 'pizza', 'italian', 'quick-meal'],
    badges: ['sale', 'popular'],
    weight: 370,
    dimensions: { width: 28, height: 4, depth: 28 },
    createdAt: ts('2025-02-18T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-27'),
    name: 'Vanilla Ice Cream',
    slug: 'vanilla-ice-cream',
    description:
      'Premium vanilla bean ice cream made with real Madagascar vanilla. Ultra creamy and indulgent.',
    price: 6.99,
    originalPrice: 6.99,
    unit: 'each',
    category: cat('frozen-foods'),
    imageUrl: '/images/products/ice-cream.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 289,
    inStock: true,
    stockQuantity: 50,
    nutritionFacts: {
      calories: 250,
      protein: 4,
      carbs: 28,
      fat: 14,
      fiber: 0,
      sodium: 70,
    },
    tags: ['frozen', 'ice-cream', 'dessert', 'vanilla'],
    badges: ['popular'],
    weight: 1420,
    dimensions: { width: 14, height: 12, depth: 10 },
    createdAt: ts('2025-01-30T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-28'),
    name: 'Frozen Vegetable Medley',
    slug: 'frozen-vegetable-medley',
    description:
      'A colourful mix of broccoli, carrots, corn, and green beans. Flash-frozen to lock in nutrients.',
    price: 3.49,
    originalPrice: 3.49,
    unit: 'each',
    category: cat('frozen-foods'),
    imageUrl: '/images/products/frozen-vegetables.jpg',
    modelUrl: null,
    rating: 4.0,
    reviewCount: 134,
    inStock: true,
    stockQuantity: 80,
    nutritionFacts: {
      calories: 65,
      protein: 3,
      carbs: 13,
      fat: 0,
      fiber: 4,
      sodium: 30,
    },
    tags: ['frozen', 'vegetables', 'mixed', 'healthy'],
    badges: [],
    weight: 454,
    dimensions: { width: 16, height: 4, depth: 22 },
    createdAt: ts('2025-03-12T10:00:00Z'),
    updatedAt: ts('2025-05-25T10:00:00Z'),
  },
  {
    id: id('prod-29'),
    name: 'Crispy Fish Sticks',
    slug: 'crispy-fish-sticks',
    description:
      'Golden, crispy fish sticks made with wild-caught Alaska pollock. A kid-friendly dinner favourite.',
    price: 6.49,
    originalPrice: 7.49,
    unit: 'pack',
    category: cat('frozen-foods'),
    imageUrl: '/images/products/fish-sticks.jpg',
    modelUrl: null,
    rating: 4.2,
    reviewCount: 167,
    inStock: true,
    stockQuantity: 55,
    nutritionFacts: {
      calories: 230,
      protein: 11,
      carbs: 22,
      fat: 11,
      fiber: 1,
      sodium: 390,
    },
    tags: ['frozen', 'fish', 'kids', 'quick-meal'],
    badges: ['sale'],
    weight: 340,
    dimensions: { width: 20, height: 4, depth: 14 },
    createdAt: ts('2025-04-05T10:00:00Z'),
    updatedAt: ts('2025-06-03T10:00:00Z'),
  },

  // -----------------------------------------------------------------------
  // Pantry Staples
  // -----------------------------------------------------------------------
  {
    id: id('prod-30'),
    name: 'Extra Virgin Olive Oil',
    slug: 'extra-virgin-olive-oil',
    description:
      'Cold-pressed extra virgin olive oil from Mediterranean olives. Rich, fruity flavour for dressings and cooking.',
    price: 11.99,
    originalPrice: 11.99,
    unit: 'each',
    category: cat('pantry-staples'),
    imageUrl: '/images/products/olive-oil.jpg',
    modelUrl: null,
    rating: 4.8,
    reviewCount: 378,
    inStock: true,
    stockQuantity: 65,
    nutritionFacts: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
      fiber: 0,
      sodium: 0,
    },
    tags: ['oil', 'olive', 'cooking', 'mediterranean', 'essential'],
    badges: ['popular'],
    weight: 750,
    dimensions: { width: 8, height: 26, depth: 8 },
    createdAt: ts('2025-01-14T10:00:00Z'),
    updatedAt: ts('2025-06-01T10:00:00Z'),
  },
  {
    id: id('prod-31'),
    name: 'Penne Rigate Pasta',
    slug: 'penne-rigate-pasta',
    description:
      'Bronze-cut penne rigate made from 100% durum wheat semolina. Holds sauce perfectly in every groove.',
    price: 2.49,
    originalPrice: 2.49,
    unit: 'each',
    category: cat('pantry-staples'),
    imageUrl: '/images/products/pasta.jpg',
    modelUrl: null,
    rating: 4.5,
    reviewCount: 212,
    inStock: true,
    stockQuantity: 140,
    nutritionFacts: {
      calories: 200,
      protein: 7,
      carbs: 42,
      fat: 1,
      fiber: 2,
      sodium: 0,
    },
    tags: ['pasta', 'italian', 'staple', 'carbs'],
    badges: [],
    weight: 500,
    dimensions: { width: 8, height: 24, depth: 5 },
    createdAt: ts('2025-01-20T10:00:00Z'),
    updatedAt: ts('2025-05-18T10:00:00Z'),
  },
  {
    id: id('prod-32'),
    name: 'Jasmine Rice',
    slug: 'jasmine-rice',
    description:
      'Fragrant Thai jasmine rice with a delicate floral aroma. Long grain that cooks up fluffy and slightly sticky.',
    price: 6.99,
    originalPrice: 7.99,
    unit: 'each',
    category: cat('pantry-staples'),
    imageUrl: '/images/products/rice.jpg',
    modelUrl: null,
    rating: 4.6,
    reviewCount: 289,
    inStock: true,
    stockQuantity: 95,
    nutritionFacts: {
      calories: 160,
      protein: 3,
      carbs: 36,
      fat: 0,
      fiber: 0,
      sodium: 0,
    },
    tags: ['rice', 'jasmine', 'thai', 'staple', 'grain'],
    badges: ['sale'],
    weight: 2268,
    dimensions: { width: 16, height: 24, depth: 10 },
    createdAt: ts('2025-02-08T10:00:00Z'),
    updatedAt: ts('2025-06-02T10:00:00Z'),
  },
  {
    id: id('prod-33'),
    name: 'Crushed Tomatoes',
    slug: 'crushed-tomatoes',
    description:
      'San Marzano-style crushed tomatoes in rich puree. The perfect base for pasta sauces, soups, and stews.',
    price: 2.99,
    originalPrice: 2.99,
    unit: 'each',
    category: cat('pantry-staples'),
    imageUrl: '/images/products/canned-tomatoes.jpg',
    modelUrl: null,
    rating: 4.4,
    reviewCount: 198,
    inStock: true,
    stockQuantity: 110,
    nutritionFacts: {
      calories: 20,
      protein: 1,
      carbs: 4,
      fat: 0,
      fiber: 1,
      sodium: 150,
    },
    tags: ['canned', 'tomatoes', 'sauce', 'italian', 'staple'],
    badges: [],
    weight: 794,
    dimensions: { width: 10, height: 12, depth: 10 },
    createdAt: ts('2025-01-28T10:00:00Z'),
    updatedAt: ts('2025-05-22T10:00:00Z'),
  },
  {
    id: id('prod-34'),
    name: 'Raw Wildflower Honey',
    slug: 'raw-wildflower-honey',
    description:
      'Pure, unfiltered wildflower honey harvested from local apiaries. Rich amber colour with floral complexity.',
    price: 9.99,
    originalPrice: 12.49,
    unit: 'each',
    category: cat('pantry-staples'),
    imageUrl: '/images/products/honey.jpg',
    modelUrl: null,
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    stockQuantity: 40,
    nutritionFacts: {
      calories: 60,
      protein: 0,
      carbs: 17,
      fat: 0,
      fiber: 0,
      sodium: 0,
    },
    tags: ['honey', 'sweetener', 'natural', 'raw', 'local'],
    badges: ['organic', 'sale'],
    weight: 454,
    dimensions: { width: 8, height: 14, depth: 8 },
    createdAt: ts('2025-03-20T10:00:00Z'),
    updatedAt: ts('2025-06-04T10:00:00Z'),
  },
];

// ---------------------------------------------------------------------------
// Accessor Functions
// ---------------------------------------------------------------------------

/** Returns all categories sorted by display order. */
export function getMockCategories(): GroceryCategory[] {
  return [...MOCK_CATEGORIES].sort((a, b) => a.order - b.order);
}

/** Returns all products. */
export function getMockProducts(): GroceryProduct[] {
  return [...MOCK_PRODUCTS];
}

/** Returns products belonging to the given category slug. */
export function getMockProductsByCategory(slug: string): GroceryProduct[] {
  return MOCK_PRODUCTS.filter((p) => p.category.slug === slug);
}

/** Returns a single product by its slug, or `undefined` if not found. */
export function getMockProductBySlug(
  slug: string,
): GroceryProduct | undefined {
  return MOCK_PRODUCTS.find((p) => p.slug === slug);
}
